### ISSUE TITLE
Extension icon is not visible in dark mode (Firefox)

### ISSUE THREAD

**Issue by coskunkut** [Langenscheiss/bibitnow#10]
When using dark mode (default dark theme or any theme with dark background color) in Firefox (68.0.1), extension icon is not visible.

![Screenshot_20190826_144903](https://user-images.githubusercontent.com/42997083/63688993-75ed5c80-c811-11e9-8fd3-5728b84c90b5.png)

Thanks for this handy extension!

**Comment by Langenscheiss** [comment]
Thanks for letting me know :) Will try to fix it.
I did not have much time the last 10 months (new job, new life situation etc., the usual stuff), but  I am planning on maintaining the plugin more regularly now. Hopefully, that works :)

**Comment by Langenscheiss** [comment]
![TestShot](https://user-images.githubusercontent.com/16846066/63693341-1d6b8e80-c814-11e9-8152-c95f200cb43a.png)

How about that? In regular mode, the icon barely changes like this

**Comment by coskunkut** [comment]
That's certainly better! Thanks for maintaining the plugin, it saved me a lot of time during my MSc.
