### ISSUE TITLE
Unable to access the full source code URL

### ISSUE THREAD

**Issue by YukinoHayakawa** [Langenscheiss/bibitnow#11]
I could not open the link https://aqpl.mc2.chalmers.se/PDSU/files/BibItNowMultiBrowser.zip 

But I'm not sure is this only related with my network or it indicates a server problem.

**Comment by Langenscheiss** [comment]
Yes, you're right. I will upload the zip here.

**Comment by YukinoHayakawa** [comment]
Thank you very much.

**Comment by Langenscheiss** [comment]
Sorry it took me so long. I was really busy, and this was kind of on my back log. I have now updated the multibrowser version as zip. This has all the source. Note that the safari version probabyl does not work.
