### ISSUE TITLE
Support @online format

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#13]
IMHO this uses `@misc` way too often.

You can also use `@online` to cite sources, which is IMHO more elegant and semantically more correct. See https://tex.stackexchange.com/q/55999/98645

So could this be integrated?

At least biblatex and biber do support this format.

**Comment by Langenscheiss** [comment]
Hi.
Sorry for the silence, but I guess you are aware of the situation. Yes, it's a one-liner to fix it. I have done that now. Will be in the next release. 

P.S.: I might find some time today and tomorrow. At the moment, I only have time to maintain the addon working, so I will try to do that. But small fixes like this can be done of course.

Best,

Langenscheiss

**Comment by Langenscheiss** [comment]
Should be fixed with 0.863
