### ISSUE TITLE
(Optionally) Use date instead of year/month

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#14]
Instead of `years/month` it would be good to be able to use `date`, with an exact date in [ISO format](https://xkcd.com/1179/), which specifies the day, too. (at least lualatex/biber support this)

**Comment by Langenscheiss** [comment]
Thanks again! Another easy thing to add. Will be in next release.

**Comment by Langenscheiss** [comment]
In 0.863, the iso date exists as an additional field that can be turned on in the bibtex specific options. It's off by default, but you can turn it on and disable year and month to achieve what you want.
