### ISSUE TITLE
Automatically use permalink for Wikipedia articles

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#17]
It would be nice to automatically use permalinks for Wikipedia articles

e.g.
https://en.wikipedia.org/wiki/Industry_4.0

would be (today) converted into 
https://en.wikipedia.org/w/index.php?title=Industry_4.0&oldid=951608890

(use the link in the left sidebar or the version history tool of Wikipedia for that)

**Comment by rugk** [comment]
Actually Wikipedia has a cite tool, but that does not honor the settings we have (like previously requested `@online` etc.): https://en.wikipedia.org/w/index.php?title=Special:CiteThisPage&page=Industry_4.0&id=951608890&wpFormIdentifier=titleform#BibTeX_entry

**Comment by rugk** [comment]
Here Wikimedia seems to track their progress on supporting the nice features we have here (`@online` etc.): https://phabricator.wikimedia.org/T188854

**Comment by Langenscheiss** [comment]
This can probably be solved by writing a simply adjuster for wikimedia. Same goes for the date.

**Comment by Langenscheiss** [comment]
It turns out that wikipedia provides information using schema.org json, which bibitnow can parse. So I am reading this instead now. Just wondering whether I should include "contributors to ..." as authors.

**Comment by Langenscheiss** [comment]
In 0.882, I have left in authors for Wikipedia, but I am actually not sure whether this is the correct way to cite wiki articles. Any insight on that?
