### ISSUE TITLE
Wikipedia: Uses wrong date

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#18]
https://en.wikipedia.org/w/index.php?title=Industry_4.0&oldid=951608890 has been changed at 
> 00:05, 18 April 2020

However, the add-on generates the link date 2020-04-20 for that:
```
@online{BibEntry2020Apr,
	title = {{Industry 4.0 - Wikipedia}},
	year = {2020},
	month = {Apr},
	date = {2020-04-20},
	urldate = {2020-04-22},
	url = {https://en.wikipedia.org/w/index.php?title=Industry_4.0&oldid=951608890}
}
```

**Comment by Langenscheiss** [comment]
Yeah, just requires a site adjuster for wiki with a preferred meta tag for the date. That should be in the next release.
Thx.

**Comment by Langenscheiss** [comment]
Wiki should be working as you asked now

**Comment by rugk** [comment]
Thanks! :tada:
