### ISSUE TITLE
Automatically detect langauge

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#19]
It would be great, if this could also support the `language` key for biber/biblatex.

That may be extractable by some meta head data, or by the common HTML attribute [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) at the `html`, which is also commonly.

THe problem is just, it needs to make the ISO tags to the long names recognized by biblatex/biber, e.g. "en" to "english" (AFAIK they do not recognize the short codes).

Maybe also provide the ability to set a "main" language you speak by yourself/write the document in, where the tag is omitted then, because that is obvious. (But that is not necessary, AFAIK biber does that, too, anyway.)

**Comment by Langenscheiss** [comment]
Once it recognizes languages (by matching rules), converting between long/short names is trivial, and just another option to the different parsers. But implementing language detection first requires to go through a lot of html sources and me figuring out which meta tags are usually used to indicate language. Will take time, but I put it on the list.

**Comment by rugk** [comment]
IMHO you don't need all that meta tags. As said, the most common one is this:
> by the common HTML attribute lang at the html, which is also commonly.

**Comment by Langenscheiss** [comment]
Made it into 0.882
