### ISSUE TITLE
Allow users to change tabs to spaces in .bib output?

### ISSUE THREAD

**Issue by episanty** [Langenscheiss/bibitnow#23]
I know this is extremely picky, given that the extension is already pretty close to perfect, but... would it be possible to add a configuration option that allows the user to replace the initial tab in each line of the bibtex output with a given number of spaces? This could go under `Advanced settings for Bibtex format`, say.

If not, then this can be solved with a search+replace postprocessing, but at least for me it would put the output fully into copy-and-forget territory.

**Comment by Langenscheiss** [comment]
Sure, that should not pose any issue at all :) 
Fixed in next version. The default will be tab, but you can change it to whatever space you like.

**Comment by episanty** [comment]
Many thanks!

**Comment by Langenscheiss** [comment]
Fixed in version 0.886
