### ISSUE TITLE
Feature request: support of all utf-8 characters

### ISSUE THREAD

**Issue by AdamJel** [Langenscheiss/bibitnow#26]
Hello,

would it be possible to support even special characters in a way, that characters like ě,š,č,ř,ž,ý,á,í,é are copied?

## How to reproduce the issue:
Bib on this link: [české URL](https://prirucka.ujc.cas.cz/?slovo=normalizace)

## Expected output:
```
@online{BibEntry2004,
	title = {Internetová jazyková příručka},
	year = {2004},
	publisher = {Ústav pro jazyk český (Akademie věd ČR},
	note = {[Online; accessed 9. Jun. 2020]},
	url = {https://prirucka.ujc.cas.cz/?slovo=normalizace}
}
```

## Actual output:
```
@online{BibEntry2004,
	title = {{Internetov{\ifmmode\acute{a}\else\'{a}\fi} jazykov{\ifmmode\acute{a}\else\'{a}\fi} p{\ifmmode\check{r}\else\v{r}\fi}{\ifmmode\acute{\imath}\else\'{\i}\fi}ru{\ifmmode\check{c}\else\v{c}\fi}ka}},
	year = {2004},
	publisher = {{\ifmmode\acute{U}\else\'{U}\fi}stav pro jazyk {\ifmmode\check{c}\else\v{c}\fi}esk{\ifmmode\acute{y}\else\'{y}\fi} (Akademie v{\ifmmode\check{e}\else\v{e}\fi}d {\ifmmode\check{C}\else\v{C}\fi}R)},
	note = {[Online; accessed 9. Jun. 2020]},
	url = {https://prirucka.ujc.cas.cz/?slovo=normalizace}
}
```

Thank you

**Comment by Langenscheiss** [comment]
Hi.
Yes, this is possible for most utf8 characters including the ones you stated, but since the actual output produces a correct citation when compiling, it was not on priority so far. I think it can make it into the next version.

**Comment by AdamJel** [comment]
Okej, that's great. Thank you

**Comment by Langenscheiss** [comment]
In version 0.892, you can choose between replacing all characters, replacing only non-letter characters (recommended if some control characters, non-standard punctuation/hyphenation or math expressions appear) and replacing nothing. However, even if no characters are replaced, multi-letter author initials are still wrapped into a \relax command by default. This, however, can also be turned off with another bibtex option.

**Comment by Langenscheiss** [comment]
I have updated the extension. Let me know if this works for you.

**Comment by AdamJel** [comment]
Hi, sorry for such a delay. I had been busy with my deadline. Yes, I think this is good. I am now opinionated probably as much as you are, but nevertheless I find it satisfying.
