### ISSUE TITLE
Feature request: indentation by spaces

### ISSUE THREAD

**Issue by AdamJel** [Langenscheiss/bibitnow#27]
# Indentation by spaces
Hi, it would be nice, if it was possible to set, that indentation in generated bib item is either tab (current) or (perhaps arbitrary number of) spaces.

## Expected behaviour:
4 spaces [U+0020] as indentation

![spaces](https://user-images.githubusercontent.com/33990009/84374409-3f38d500-abde-11ea-98fa-32359f0cddfa.png)

## Actual behaviour:
1 tab [U+0009] as indentation

![tabs](https://user-images.githubusercontent.com/33990009/84374422-4364f280-abde-11ea-8374-de815eba3df7.png)

## Reasoning:
To be consistent with rest of the code. Even though simple search and replace do the job, one must remember it. I myself never use tab for indentation, so a simple set parameter would be nice solution.

Thank you

**Comment by Langenscheiss** [comment]
Hi

This option is already available!??? Check the bibtex options. You can set an arbitary number of spaced or tabs for indentation :)

**Comment by AdamJel** [comment]
@Langenscheiss Oh, I am sorry, I missed that. 

Also, could you be more specific, where can I find the settings? Is it available through the Custom citation formats? I must be blind or something :)

**Comment by Langenscheiss** [comment]
"+More settings" button in the popup, then scroll to the setting.

**Comment by AdamJel** [comment]
Thank you. I did miss that. I was only checking the settings available from firefox extension list. Thank you and sorry about the fuzz.

**Comment by Langenscheiss** [comment]
Hmm, I see. That's valuable input in fact. Maybe I should add a warning sentence to the custom citation format dialogue. I suppose you switched to the global option panel because of the "Custom->" button right underneath the format selector. That might distract from the "+More settings" button. Do you have an idea to make it clearer? Maybe i call it "Add->" instead so one is not so easily tricked into believe that custom leads to "custom settings".

**Comment by AdamJel** [comment]
I'd say, the first problem is, that there are more than one place to set up things. If you check Privacy Badger Firefox extension for example, you can enter settings from both places - from icon while browsing a webpage and from extension list. But both options take you to ONE settings page. So there cant by a confusion where is what.

But let's presume, you have and want to have two different access places for settings. My very personal problem was, that I literally didn't see the option in 'button' menu. It's gray colour, almost perfectly blended into background. I simply misted it. So, the easy solution seems to be, just make it more visible. Perhaps just by changing the font colour to black.

PS: I did change the settings from button menu once. So I 'should' know, there is such options, but it is such a minor thing, I completely forgot about it and I was not able to find it again.

![2020-06-14 00_38_32-](https://user-images.githubusercontent.com/33990009/84580659-1892be00-add9-11ea-8f0b-61c5cdf9efe3.png)

**Comment by Langenscheiss** [comment]
These options are format specific, so having them all in one place is impractical. It's much faster to simply access them like this from the popup, and you only see what you need for the specific format.

I agree, however, that it would help to make it more visible, even though I think "invisible" is an exaggeration. The problem here is also that it depends heavily on the screen settings. On my screen it looks fine. But one can think about a different color, font, font size etc.

**Comment by AdamJel** [comment]
> 
> 
> These options are format specific, so having them all in one place is impractical. It's much faster to simply access them like this from the popup, and you only see what you need for the specific format.
> 
> I agree, however, that it would help to make it more visible, even though I think "invisible" is an exaggeration. The problem here is also that it depends heavily on the screen settings. On my screen it looks fine. But one can think about a different colour, font, font size etc.

Well of course these things are very subjective. I am actually not proposing anything, just sharing my own experience.

But I must target one thing, which is your response time and support. Both are excellent and I appreciate both very much. It makes the project much more appealing.

**Comment by Langenscheiss** [comment]
Ok, I have changed visibility for 0.892. It's a bit into your face now, but maybe it's better this way. I am not very good at styling though...

Regarding the options, there is just some things that need to be separated. The panels allowing you to define redirection schemes and citation formats, or the proxy options or the bibkey customization are all quite advanced and not specific to the format options. Most users are not going to use those features anyhow, as they are aimed at power users. But the options for the output formats are more relevant to common users, as many people have different preferences (such as indentation for example). To have those options as close to the output as possible is better imo. Adding global options to those panels would just confuse and clutter things.

**Comment by Langenscheiss** [comment]
I have made the buttons more visible, and furthermore, I have added a header to the global option page screaming at people that the citation format options are available from the "+ Format Settings" button in the popup. I hope this will be enough for now. 

Another possibility is to also make these options available from the global page. This however causes issues if a user opens the popup on the global option page and then edits the options from the popup while the option page is open. That will mean that I would have to tell the global page to update whenever the user does this. It's probably possible, but causes a lot of fuzz and time to implement. For now, this needs to suffice.

**Comment by AdamJel** [comment]
## Your current fix
I agree that your current fix is sufficient. Since you reason for two option menus, it may be even ideal.

## Proposed alternative
The mentioned solution of having the format in both places doesn't seem very good to me neither. 1) As you showed, it proposes some sort of "race conditions", which would have to be addressed. 2) It is inconsistent to concept. Either the concept it to have just one menu, or, as you reason for, to have two menus. Then options should be available from one or another, imo, not from both.

## Reasoning
I understand and agree with your reasoning. It makes perfect sense. But I'd add that the context matters.

### Scenario 1:
I am not opinionated (with no previous experience with browser extensions) user with fresh instalment of browser - that is with no extensions. In this case, your reasoning is 100 % true, since the way of changing options would be newly learned and, as you showed, it is more efficient this way (less steps).

### Scenario 2:
I am opinionated user (I have 10+ extensions installed) and as such, I am sort of taught of doing things rather specific way. In this case, if all other extensions have only global page with options, accessible either through link from pop-up or from extension list page, then bibitnow extension is inconsistent in respect to others and thus represents mental overhead for me. Then your reasoning is <100 % true. It is important to say though, that scenario 2, as I described it here, is concluded from my subjective experience only and is not representative. 

### Other extensions
I just checked how is it implemented in other extensions, I have installed, and this is result: 
- total number of installed extensions = 13
- num. of exts. with pop-up menu only = 2
- num. of exts. with global page menu only = 10
- num. of exts. with both menu options = 1 (2 if I count bibitnow)

The Firefox native way is also one global page. E.g. pop-up of account "extension":

![firefox_native_way](https://user-images.githubusercontent.com/33990009/84592778-58dd5500-ae48-11ea-8801-5c8e7d875e3e.png)

## Conclusion
Design and concept design are subjective disciplines. Your current fix is sufficient imo. Though it is usually done differently.

**Comment by Langenscheiss** [comment]
Thanks for this inspiring conversation :)
Yes, it is subjective and yes, my solution is definitely non-standard, but I firmly believe that with proper design adjustments, the "mental overhead" is bearable. Every time you open the popup, you see two buttons (now at least, with better design): "+ Format Settings", and "Global options->". I think after like 5 times, you will realize and memorize what each of those things are doing, and every time you open the popup again, you will see those two buttons again. I think the main issue here was/is in the current version that the buttons are indeed not super visible. 
And about the non-standard way, I still think that even with "mental overhead" (which tbh is a bit of an exaggeration of the actual severity of the problem), the popup workflow is faster, even if its different than what one is used to from other extensions. 
 So i consciously choose to deviate a bit from the standard here because it makes sense.

**Comment by AdamJel** [comment]
> Thanks for this inspiring conversation :)

Pleasure on my side :)

I thought I would have answered by now, but I dont thave the time right now. So I just want to let you know, that I intent to reply few days later.

**Comment by AdamJel** [comment]
Hi, as stated in my reply for other commit, sorry for such a delay.

I agree that fixing "just" the design here is justifiable and the overall issue is therefore closed.

But let me comment on the topic of mental overhead anyway. Yes, if we think about it, concerning this issue, in absolute terms (may it be actual energy in Joules consumed in brain, or other) it is surely negligible, and thus it is fine to say that the term is an exaggeration. My argument was more of a principled nature. That is, I wanted to point out, there is something like mental overhead to consider. And while I agree, the overhead may be consciously excepted for being too small here, I also believe, that the concept of overhead should always be taken into account.
Some reasoning for that: In my opinion, the day-to-day life is full of negligible mental overheads and it is the integral what drains your limited energy pool. I even state following: The overall ineffectiveness of (not only) scientist is equal to that integral. There is this modern (hyped even) term for concentration - deep work (such as in Cal Newport's definition) or flow. It is (nearly worshipped) state of mind, in which person is able to achieve work effectiveness much above his average. I even state, that this "flow" is, what is left after the limit of integral of mental overheads approaches zero for given period of time.
And so I believe, that it should be work and life goal to lower all these mental overheads we encounter as much as possible.
This leads to some ordinary advices like: better do it now, so you don't have to think about it later; try to avoid context switching, etc..

Above text is just brief sum of my idea on topic and should not be used as argument against particular cases :)
