### ISSUE TITLE
Uses "journal" way too often

### ISSUE THREAD

**Issue by rugk** [Langenscheiss/bibitnow#28]
Here is an example it generates:
```
@article{Herbig2020Jun,
	author = {Herbig, Daniel},
	title = {{"The Last of Us Part 2" im Test: Im Sog der Gewalt}},
	journal = {heise online},
	date = {2020-06-12},
	urldate = {2020-06-12},
	publisher = {heise Online},
	language = {german},
	url = {https://www.heise.de/tests/The-Last-of-Us-Part-2-im-Test-Im-Sog-der-Gewalt-4778572.html}
}
```

This is no journal.
Putting this under `organisation` tag may be more useful.

**Comment by Langenscheiss** [comment]
Thats true, but I have no idea how to distinguish that without handtuning. Now in case of heise, I can change that using the site adjuster and introducing this additional bibfield organization. However, to distinguish in general between online journal and organization is tricky. You have an idea? Otherwise, the only way this will be fixed is with hand tuning, which costs a lot of time that I might not always have. So this won't be fixed in the next version but maybe in the future..

**Comment by rugk** [comment]
Well… I the biggest problem was IMHO that my bib style does not print the `journal` field when using it together with `@online`. :thinking:

**Comment by rugk** [comment]
As for changing it: dunno, I would need to look into how/why it does even categorize that as a journal? :thinking:

**Comment by Langenscheiss** [comment]
I am confused now. In the above example, it clearly identifies the page as an @article and not as @online. If you want to change it to online anyhow, you can use the same script/procedure to change journal to organization.

Another thing you can try is to activate the "journal in biblatex style" compatibility option. Maybe it does print "journaltitle" in your citation style.

 For the @online type, I can give you a compatibility option allowing you to change "journal = " to "organization = ".

**Comment by rugk** [comment]
Okay okay, this was a bad example. AFAIK the same issue happened with `@online`.

**Comment by rugk** [comment]
> For the @online type, I can give you a compatibility option allowing you to change "journal = " to "organization = ".

Yeah, I guess that would be it. If it chooses `@online`, don't use `journal`.

**Comment by Langenscheiss** [comment]
Ok, that's no problem and will be in the next version :)

**Comment by Langenscheiss** [comment]
Ok, there will be an option for version 0.892. I will keep the issue open and wait if the option will be ok for you.

**Comment by Langenscheiss** [comment]
The version has been updated. Let me know if this works for you :)

**Comment by rugk** [comment]
Yeah, fine, I'll see how it works in practice. :smile:

**Comment by rugk** [comment]
Hmm, actually does not seem to work.

See e.g.
https://www.bitkom.org/Presse/Presseinformation/Jeder-Zweite-hat-bereits-online-eine-Versicherung-abgeschlossen

results in:

```
@online{BibEntry2020Jun,
	title = {{Jeder Zweite hat bereits online eine Versicherung abgeschlossen}},
	journal = {Bitkom e.V},
	date = {2020-06-15},
	urldate = {2020-06-15},
	language = {german},
	url = {https://www.bitkom.org/Presse/Presseinformation/Jeder-Zweite-hat-bereits-online-eine-Versicherung-abgeschlossen}
}
```

in 0.892

and I could not find any option to change that behaviour.

**Comment by Langenscheiss** [comment]
"Set organization if default source type" is the option

**Comment by rugk** [comment]
> I did not activate that option by default because I don't think this should be default behavior.

I think it should be **if** the default source type is `@online`. Biblatex does not define the keyword `journal` for `@online` entries, so adding it there makes no sense. It just does not get printed.

See http://www.texdoc.net/texmf-dist/doc/latex/biblatex/biblatex.pdf page 11.

**Comment by Langenscheiss** [comment]
I will see how I deal with biblatex etc. in the future. In plain Bibtex, organization is not used for that purpose so for the moment this will need to suffice and I presume you can achieve what you want. I think biblatex might need a more systemic solution.
