### ISSUE TITLE
Feature: shortcut to copy formatted citation to clipboard directly

### ISSUE THREAD

**Issue by lotard** [Langenscheiss/bibitnow#29]
Like 'alt-c' followed by 'ctrl-c' in one. Don't even need to display it.

**Comment by Langenscheiss** [comment]
Good idea. However, you will need some kind of info text telling you when the citation has been downloaded. It does not happen instantly. But it's definitely a cool feature to think about. I will try to experiment with it. Maybe, as a compromise, it will be displayed, but then copied to clipboard automatically. Also, I need to see whether the permission system actually allows clipboard interaction without additional user interaction. That might be a limiting factor beyond my control.

**Comment by Langenscheiss** [comment]
Short update. It seems like what you are asking for is possible when asking for the "write to clipboard" permission and by using the clipboard API. It would require me to raise the minimum supported browser version to 63. But when this is activated, i can let the extension copy the text to clipboard every time the citation text is marked or remarked. So for example,if you open the popup, but then you change some option and the citation text changes,it is automatically copied to clipboard again.

**Comment by Langenscheiss** [comment]
Works like a charm :) Will be in next release. Also, i will simply check for availability of the clipboard api and for permission, so if a user either cannot (too low version) or does not want to grant access, that's totally fine.

Thanks for the suggestion :)

**Comment by Langenscheiss** [comment]
In 0.893, there is a link to copy options in the popup. In the option menu, you can turn on automatic copies (requires additional permission and hence is not activated by default). Then, you can press Alt+W or any other configurable shortcut to open the popup in auto copy mode. This spares you the Ctrl+C. There are also several other options you can play with, including hiding the "Copy options->" link.

**Comment by lotard** [comment]
works like a charm 👍
