### ISSUE TITLE
Bug: misidentified abstracts

### ISSUE THREAD

**Issue by lotard** [Langenscheiss/bibitnow#30]
Seems to affect ScienceDirect , e.g. https://www.sciencedirect.com/science/article/pii/S0092867413003929

The abstract starts: 'Download : Download high-res image (133KB)Download : Download full-size image Highlights xn--k1h Master transcription factors form', indicating it is picked from Highlights, rather than Summary.

**Comment by Langenscheiss** [comment]
Yeah, happens every now and then. I will adjust science direct adjuster for the next release. I have an internal verification tool that enables me to identify those issues more quickly, but i did not have the time to add all publishers to it yet.

**Comment by Langenscheiss** [comment]
In 0.893, it starts from Summary. Cause was a greedy regexp :)
