### ISSUE TITLE
Source download

### ISSUE THREAD

**Issue by oatmealm** [Langenscheiss/bibitnow#35]
Hi. The source code link for the extensions itself does not seem to work again. I'm interested in testing against my university's library. 

https://aqpl.mc2.chalmers.se/PDSU/files/BibItNowMultiBrowser.zip

**Comment by Langenscheiss** [comment]
Sorry, I should remove the link. The full source is in the main folder of the repository already, as zip file.

**Comment by oatmealm** [comment]
Thanks! I'll have a look.
