### ISSUE TITLE
Bug: get author if index is out of bounds

### ISSUE THREAD

**Issue by maarli** [Langenscheiss/bibitnow#36]
If one has a custom citation format like this
`[
	{
		"req": false,
		"bibfields": [
			[
				"authors",
				1,
				false,
				"",
				"",
				[]
			]
		]
	}
]`

I would expect to get an empty result if there is only one author. But one gets all three entries of the only one author.
I suggest the following change in the code in /background/parser/background_parse_bib.js:1594:
```javascript
  else if (Array.isArray(data)) {
	if(idx >= dataLength || idx <= -dataLength)
		data = "";
	else
		//if array, take array element, continue reduction
		data = idx >= 0 ? data[idx%dataLength] : data[dataLength-1 - ((-idx-1)%dataLength)];
   }
```

**Comment by Langenscheiss** [comment]
Hi.
Yeah, I wasn't sure what the best out of bounds behavior would be there. But you can also solve this issue with regexps I think, I mean if you want to have an empty result if there is no second author. You can test whether the author output has a certain format that has only one author. However, I am thinking about changing it to what you suggested in the next version. I do see the potential benefit.

**Comment by Langenscheiss** [comment]
Hi.
I have changed the behavior now with the following compromise. If the idx is positively out of bounds, you get an empty result. If the idx is negative, it is only considered out of bounds as soon as (dataLength+idx) is negative. In this way, you can achieve what you like while still allowing to access the array from the back using negative indices. I think this offers most flexibility.

Hope the update comes soon. Time and resources is always the issue :)

**Comment by maarli** [comment]
Sounds great. Sure I know the time issue very well. Thanks a lot.

**Comment by Langenscheiss** [comment]
You should get an empty string now when out of bounds.

**Comment by maarli** [comment]
Thank you very much for the fast correction.

But the problem now is that if we have now a second author the further process is aborted in line 1655 in the new version. And that results in an empty string if the second author exists.
The reason for that is that data is an array if there is a second author but at 1655 it is expected to be a string.
But here the array of the author have to be processed.

**Comment by Langenscheiss** [comment]
Hi.
No, it's not strange, it's oversight on my part. I forgot that I intended the possibility to stringify an array, and forgot to check for that afterwards. Hence, the above format gives nothing. You either make it "authors", 1, 0, or wait for the next build :)

**Comment by maarli** [comment]
Okay, cool. For the moment I took the 1,0 :-)

**Comment by Langenscheiss** [comment]
In 0.899, it should work again :)
