### ISSUE TITLE
Request: save URL

### ISSUE THREAD

**Issue by lotard** [Langenscheiss/bibitnow#39]
Would it be possible for bibitnow to always include the page url in the citation (under key:url)? Or is there some way I set it up myself?

**Comment by Langenscheiss** [comment]
With the bibtex format, this is already possible under format options. If you scroll down, you will find a checkbox "Show URL" with a drop down option afterwards. Set this option to "Always".

**Comment by lotard** [comment]
Ah, way ahead of me, thanks!
