### ISSUE TITLE
Month field should be integer

### ISSUE THREAD

**Issue by DL6ER** [Langenscheiss/bibitnow#4]
When using BibItNow!, you get months in abbreviated form, like
```
month = {Apr},
```
However, [Biber](http://biblatex-biber.sourceforge.net/) (the official BibTeX replacement which supports a lot of additional features), does not really like these abbreviations and complains:

> **WARN** - month field 'Apr' in entry 'TestArticle' is not an integer - this will probably not sort properly.

Reading a few documents (esp. the [`biblatex` package documentation](https://mirror.informatik.hs-fulda.de/tex-archive/macros/latex/contrib/biblatex/doc/biblatex.pdf)), the official documentation states
> **month**
> The publication month. This must be an integer, not an ordinal or a string. Don’t say `month={January}` but `month={1}`. The bibliography style converts this to a language dependent string or ordinal where required. This field is a literal field only when given explicitly in the data (for plain BibTeX compatibility for example).

(see page 22).

Can the output of BibItNow! be changed to return integer numbers which will work everywhere? I'd be happy with submitting a pull request myself, but it doesn't seem like the corresponding code is exposed for pull requests (seems to be in `background/parser/background_parse_bib.js:1439 but it hard to say without reading the entire code).

**Comment by Langenscheiss** [comment]
No problem. I will simply add an option to the bibtex output to put months as integers. Does it have to be an integer with leading 0 ?

**Comment by DL6ER** [comment]
> Does it have to be an integer with leading 0 ?

No, `4`, for example, works fine for April.

**Comment by Langenscheiss** [comment]
Great. This is a small fix that I can probably push today or tomorrow, together with another small fix. Thanks!

**Comment by Langenscheiss** [comment]
Yep, fixed internally, and will be pushed with next build. The default will be abbreviated months, but you can set it to integer format via the Bibtex option menu.

**Comment by DL6ER** [comment]
Working as expected, thank you!

![untitled_months](https://user-images.githubusercontent.com/16748619/40117132-507d39e0-5916-11e8-8184-3e595ebff7e5.png)
