### ISSUE TITLE
Arxiv url replaced by zenodo url

### ISSUE THREAD

**Issue by enajx** [Langenscheiss/bibitnow#47]
When getting the bib ref from an arxiv paper, it automatically replaces the url by a zenodo url, is there an option to change this and get the arxiv url on the ref?

**Comment by Langenscheiss** [comment]
Strange, can you link me to a paper where you get this. When I use this link for example

https://arxiv.org/abs/2004.01469

the url obtained in the bibtex format is

url = {https://arxiv.org/abs/2004.01469v2}

on my end. This seems to be the correct url.

In case you are behind a proxy or something that replaces URLs, there is an option to change that in the general options menu.

**Comment by enajx** [comment]
This one:

[https://arxiv.org/abs/1803.10122](https://arxiv.org/abs/1803.10122)

gives me:

url = {https://doi.org/10.5281/zenodo.1207631}

rather than the arxiv version.

**Comment by Langenscheiss** [comment]
Oh, I see. You need to open the format options and then disable the option "If available, set DOI link as URL. Let me know if that works (it does on my end, but perhaps the option is broken in some unexpected way)

**Comment by owoodhansen** [comment]
> That solved it, thank you!

Enajx, do you mind explaining where you found that option "If available, set DOI link as URL". I can't find it at all. I'm using APA style referencing and I just want the doi as an url, not the url of the publisher. I can only seem to get either the latter or the doi as text, not as an url.
