### ISSUE TITLE
Issue with Abstract for Science Journals

### ISSUE THREAD

**Issue by MoshJosh** [Langenscheiss/bibitnow#48]
Hi guys,
first of all a big thank you for this really nice plug in @Langenscheiss @STDSU 
A realized that since a few month Science has changed their web page and BibItNow captures only a truncated abstract (at least for EndNote). I posted an example below

%0 Journal Article
%F Chen2021Dec
%A Chen, Jennifer S.
%A Chow, Ryan D.
%A Song, Eric
%A Mao, Tianyang
%A Israelow, Benjamin
%A Kamath, Kathy
%A Bozekowski, Joel
%A Haynes, Winston A.
%A Filler, Renata B.
%A Menasche, Bridget L.
%A Wei, Jin
%A Alfajaro, Mia Madel
%A Song, Wenzhi
%A Peng, Lei
%A Carter, Lauren
%A Weinstein, Jason S.
%A Gowthaman, Uthaman
%A Chen, Sidi
%A Craft, Joe
%A Shon, John C.
%A Iwasaki, Akiko
%A Wilen, Craig B.
%A Eisenbarth, Stephanie C.
%T High-affinity, neutralizing antibodies to SARS-CoV-2 can be made without T follicular helper cells
%J Sci. Immunol.
%U https://www.science.org/doi/10.1126/sciimmunol.abl5652
%D 2021
%8 2021/12/16/
%I American Association for the Advancement of Science
%X T follicular helper (Tfh) cells are the conventional drivers of protective, germinal center (GC)-based antiviral antibody responses. However, loss of Tfh cells and GCs has been observed in patients...

**Comment by Langenscheiss** [comment]
Yes, science is broken. I will try to fix it next week.

**Comment by Langenscheiss** [comment]
I fixed science and many other sites in the latest version 0.906

**Comment by MoshJosh** [comment]
Thanks a lot, much appreciated...just tested Science but works fine as far as I can tell.
