### ISSUE TITLE
DOI is missed on http://adsabs.harvard.edu

### ISSUE THREAD

**Issue by DL6ER** [Langenscheiss/bibitnow#5]
Consider e.g. the page http://adsabs.harvard.edu/abs/2017MNRAS.466.3293P
The generated Bibtex record is lacking the DOI although being available on the page:
```
@article{Peters2017,
	author = {Peters, Thomas and Naab, Thorsten and Walch, Stefanie and Glover, Simon C. O. and Girichidis, Philipp and Pellegrini, Eric and Klessen, Ralf S. and W{\ifmmode \ddot{u} \else \"{u}\fi}nsch, Richard and Gatto, Andrea and Baczynski, Christian},
	title = {{The SILCC project - IV. Impact of dissociating and ionizing radiation on the interstellar medium and H{$\alpha$} emission as a tracer of the star formation rate}},
	journal = {MNRAS},
	volume = {466},
	pages = {3293--3308},
	year = {2017},
	month = {Apr},
	issn = {0035-8711},
	eprint = {1610.06569},
	url = {http://adsabs.harvard.edu/abs/2017MNRAS.466.3293P}
}
```
This is not a big deal for me as the SAO/NASA ADS Physics Abstract Service also offers a direct export of BibTeX files, just something I noted.

**Comment by Langenscheiss** [comment]
Arrg, you are right. This is some legacy behavior in the Bibtex output. It has to do with the fact that there is a preprint available. I forgot to put this out when I implemented custom fields. I will fix this for the next version. Thanks a lot for making me aware of it.

**Comment by Langenscheiss** [comment]
Alright, I am currently testing the next plugin version. As usual, the Safari version keeps me busy, but you can already try the developer version on my webpage (I have not yet relabeled it, but it is already the new version). Once I have ironed out major problems with Safari, I will update. I will most likely be done tomorrow.

**Comment by Langenscheiss** [comment]
Should be fixed now.

**Comment by DL6ER** [comment]
Seems to work as expected (at least on the link I posted above for testing). Thanks!
