### ISSUE TITLE
Incorrect space in international names

### ISSUE THREAD

**Issue by DL6ER** [Langenscheiss/bibitnow#6]
Consider the following page: http://adsabs.harvard.edu/abs/2015MNRAS.451.3340K

Here, BibItNow creates a bib record as follows:
```
@article{Kortgen2015,
	author = {K{\ifmmode \ddot{o} \else \"{o}\fi}rtgen, Bastian and Banerjee, Robi},
	[...]
}
```

However, the spacing in the if statement in the authors list leads to an unintended space when compiled with biblatex + pdftex (TeXLive 2018, unclear if this affects other variants, but it is likely):
![screenshot at 2018-05-30 11-00-36](https://user-images.githubusercontent.com/16748619/40710348-b29bffb6-63f8-11e8-8a4d-eabe9dbd61f7.png)

When manually eliminating the spaces in aboves if statement like
```
@article{Kortgen2015,
	author = {K{\ifmmode\ddot{o}\else\"{o}\fi}rtgen, Bastian and Banerjee, Robi},
	[...]
}
```
then the unintended space is gone:
![screenshot at 2018-05-30 10-59-56](https://user-images.githubusercontent.com/16748619/40710404-d49016f2-63f8-11e8-8176-86e18cba3357.png)

Please remove the spaces in the if statements are they are not needed here.

**Comment by Langenscheiss** [comment]
Should be fixed in next version.

**Comment by Langenscheiss** [comment]
Sorry for the delay. I was/am busy job wise, and I wanted to have a pass over the site adjusters. I already needed to fix some (Elsevier books, for example), so I hope I can upload the new version this weekend.

**Comment by DL6ER** [comment]
No worries, as I found (and documented here) a workaround this is not a critical bug.

**Comment by Langenscheiss** [comment]
It should now work correctly in 0.835.

**Comment by DL6ER** [comment]
Thanks. Bug resolved.
