### ISSUE TITLE
Make abbreviations configurable

### ISSUE THREAD

**Issue by DL6ER** [Langenscheiss/bibitnow#7]
Consider the following link: http://adsabs.harvard.edu/abs/1971ApJ...163..165H

The journal is given as `Astrophysical Journal`, however, BibItNow creates the following record:
```
@article{Hollenbach1971,
        [...]
	journal = {Astrophys J},
        [...]
}
```
I wonder where this `Astrophys J` is coming from. The correct abbreviation would be `ApJ` in this case, however, I'd like to have an option to always include the full journal name (`The Astrophysical Journal`) in the generated bibtex records.

**Comment by Langenscheiss** [comment]
The Astrophys J is coming from an internal library that needs updating (which however is beyond what my current time allows me to do). About the other request: you can already choose between abbreviation and full journal name, and the option works on the page you linked to. Do you mean you want both full name and abbreviation? What would be the bibtex entry then? Can one have two "journal" entries? I am not sure that works.

**Comment by Langenscheiss** [comment]
Not sure what to do here. I can of course put an option to have biblatex style journal title, meaning through the two fields "journaltitle" and "shortjournal" instead of just "journal" in the classic bibtex style. Would that help?

**Comment by DL6ER** [comment]
My bad, I looked for this option under "more settings" as well as under "Global option" but entirely missed that it is configurable on the front page of the plugin itself... I somehow just didn't expect any set-and-forget option to bi in this place. This option is everything I was asking for so no need for any further changes here.

![screenshot at 2018-05-31 09-12-20](https://user-images.githubusercontent.com/16748619/40767520-0a738154-64b3-11e8-83c4-14ad8bec85b6.png)

**Comment by Langenscheiss** [comment]
Alright, I have implemented a "Journal in biblatex style" option anyhow. So you can switch between the journal field and the "journaltitle" + "shortjournal" fields, depending on what bibliography system you are using.
